/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.np.turagencija.forme;

import java.awt.event.ActionListener;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import rs.np.turagencija.domen.TipAranzmana;
import rs.np.turagencija.komunikacija.Komunikacija;
import rs.np.turagencija.kordinator.Kordinator;

/**
 *
 * @author KORISNIK
 */
public class FormaAranzmani extends javax.swing.JFrame {

    /**
     * Creates new form FormaAranzmani
     */
    public FormaAranzmani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAranzmani = new javax.swing.JTable();
        jButtonIzmeniAranzman = new javax.swing.JButton();
        jButtonDodajAranzman = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonFiltriraj = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelUlogovani = new javax.swing.JLabel();
        jComboBoxTipovi = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemGlavnaForma = new javax.swing.JMenuItem();
        jMenuItemRadSaKlijentima = new javax.swing.JMenuItem();
        jMenuItemOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableAranzmani.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableAranzmani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableAranzmani);

        jButtonIzmeniAranzman.setText("Izmeni aranzman");
        jButtonIzmeniAranzman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniAranzmanActionPerformed(evt);
            }
        });

        jButtonDodajAranzman.setText("Dodaj aranzman");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("RAD SA ARANZMANIMA");

        jLabel2.setText("FILTRIRAJ:");

        jButtonFiltriraj.setText("Filtriraj");

        jButtonReset.setText("Resetuj pretragu");

        jLabelUlogovani.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jMenu1.setText("MENI");

        jMenuItemGlavnaForma.setText("Glavna forma");
        jMenuItemGlavnaForma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGlavnaFormaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGlavnaForma);

        jMenuItemRadSaKlijentima.setText("Klijenti");
        jMenuItemRadSaKlijentima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRadSaKlijentimaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemRadSaKlijentima);

        jMenuItemOdjava.setText("ODJAVA");
        jMenuItemOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjavaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemOdjava);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jButtonDodajAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonIzmeniAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jButtonFiltriraj))
                                            .addComponent(jButtonReset)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jComboBoxTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel1)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxTipovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFiltriraj)
                .addGap(18, 18, 18)
                .addComponent(jButtonReset)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonIzmeniAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDodajAranzman, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIzmeniAranzmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniAranzmanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIzmeniAranzmanActionPerformed

    private void jMenuItemGlavnaFormaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGlavnaFormaActionPerformed
        Kordinator.getInst().otvoriGlavnuFormu();
        this.dispose();
    }//GEN-LAST:event_jMenuItemGlavnaFormaActionPerformed

    private void jMenuItemRadSaKlijentimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRadSaKlijentimaActionPerformed
        Kordinator.getInst().otvoriPregledKlijenataFormu();
        this.dispose();
    }//GEN-LAST:event_jMenuItemRadSaKlijentimaActionPerformed

    private void jMenuItemOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjavaActionPerformed
        Komunikacija.getInstance().zaustavi();
        this.dispose();
    }//GEN-LAST:event_jMenuItemOdjavaActionPerformed

    /**
     * @param args the command line arguments
     */
    public JTable getjTableAranzmani() {
        return jTableAranzmani;
    }

    /**
     * @param args the command line arguments
     */
    public void setjTableAranzmani(JTable jTableAranzmani) {
        this.jTableAranzmani = jTableAranzmani;
    }

    public JLabel getjLabelUlogovani() {
        return jLabelUlogovani;
    }

    public void setjLabelUlogovani(JLabel jLabelUlogovani) {
        this.jLabelUlogovani = jLabelUlogovani;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajAranzman;
    private javax.swing.JButton jButtonFiltriraj;
    private javax.swing.JButton jButtonIzmeniAranzman;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<TipAranzmana> jComboBoxTipovi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemGlavnaForma;
    private javax.swing.JMenuItem jMenuItemOdjava;
    private javax.swing.JMenuItem jMenuItemRadSaKlijentima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAranzmani;
    // End of variables declaration//GEN-END:variables

    public void izmeniActionListener(ActionListener actionListener) {
        jButtonIzmeniAranzman.addActionListener(actionListener);
    }

    public void dodajActionListener(ActionListener actionListener) {
        jButtonDodajAranzman.addActionListener(actionListener);
    }

    public JComboBox<TipAranzmana> getjComboBoxTipovi() {
        return jComboBoxTipovi;
    }

    public void setjComboBoxTipovi(JComboBox<TipAranzmana> jComboBoxTipovi) {
        this.jComboBoxTipovi = jComboBoxTipovi;
    }

    public void pretraziActionListener(ActionListener actionListener) {
        jButtonFiltriraj.addActionListener(actionListener);
    }

    public void resetujActionListener(ActionListener actionListener) {
        jButtonReset.addActionListener(actionListener);
    }

}
