/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rs.np.turagencija.forme;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableColumn;
import rs.np.turagencija.komunikacija.Komunikacija;
import rs.np.turagencija.kordinator.Kordinator;

/**
 *
 * @author KORISNIK
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();

    }

    public JLabel getjLabelUlogovani() {
        return jLabelUlogovani;
    }

    public void setjLabelUlogovani(JLabel jLabelUlogovani) {
        this.jLabelUlogovani = jLabelUlogovani;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelUlogovani = new javax.swing.JLabel();
        jButtonOdjava = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRezervacije = new javax.swing.JTable();
        jButtonNapraviRezervaciju = new javax.swing.JButton();
        jButtonIzmeniRezervaciju = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkeRezervacije = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonObrisiRezervaciju = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonPretraga = new javax.swing.JButton();
        jButtonResetujPretragu = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemRadSaKlijentima = new javax.swing.JMenuItem();
        jMenuItemRadSaAranzmanima = new javax.swing.JMenuItem();
        jMenuItemRadSaUslugama = new javax.swing.JMenuItem();
        jMenuItemOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelUlogovani.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jButtonOdjava.setText("ODJAVA");

        jTableRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableRezervacije);

        jButtonNapraviRezervaciju.setText("Napravi rezervaciju");

        jButtonIzmeniRezervaciju.setText("Izmeni rezervaciju");

        jTableStavkeRezervacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavkeRezervacije);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("GLAVNA FORMA");

        jButtonObrisiRezervaciju.setText("Otkazi rezervaciju");

        jLabel2.setText("TABELA REZERVACIJA:");

        jLabel3.setText("Stavke izabrane rezervacije:");

        jLabel4.setText("Klijent (email):");

        jButtonPretraga.setText("Pretraga");

        jButtonResetujPretragu.setText("Resetuj pretragu");

        jMenu5.setText("MENI");

        jMenuItemRadSaKlijentima.setText("Klijenti");
        jMenuItemRadSaKlijentima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRadSaKlijentimaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRadSaKlijentima);

        jMenuItemRadSaAranzmanima.setText("Aranzmani");
        jMenuItemRadSaAranzmanima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRadSaAranzmanimaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRadSaAranzmanima);

        jMenuItemRadSaUslugama.setText("Fakultativne usluge");
        jMenuItemRadSaUslugama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRadSaUslugamaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemRadSaUslugama);

        jMenuItemOdjava.setText("ODJAVA");
        jMenuItemOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOdjavaActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItemOdjava);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(343, 343, 343))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonOdjava, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNapraviRezervaciju, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(jButtonIzmeniRezervaciju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonObrisiRezervaciju, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonResetujPretragu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButtonPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonResetujPretragu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonNapraviRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIzmeniRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonObrisiRezervaciju, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUlogovani, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOdjava, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRadSaKlijentimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRadSaKlijentimaActionPerformed
        Kordinator.getInst().otvoriPregledKlijenataFormu();
        this.dispose();
    }//GEN-LAST:event_jMenuItemRadSaKlijentimaActionPerformed

    private void jMenuItemRadSaAranzmanimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRadSaAranzmanimaActionPerformed
        Kordinator.getInst().otvoriFormuZaRadSaAranzmanima();
        this.dispose();
    }//GEN-LAST:event_jMenuItemRadSaAranzmanimaActionPerformed

    private void jMenuItemOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOdjavaActionPerformed
        Komunikacija.getInstance().zaustavi();
        this.dispose();
    }//GEN-LAST:event_jMenuItemOdjavaActionPerformed

    private void jMenuItemRadSaUslugamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRadSaUslugamaActionPerformed
        Kordinator.getInst().otvoriDodajUsluguFormu();
    }//GEN-LAST:event_jMenuItemRadSaUslugamaActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIzmeniRezervaciju;
    private javax.swing.JButton jButtonNapraviRezervaciju;
    private javax.swing.JButton jButtonObrisiRezervaciju;
    private javax.swing.JButton jButtonOdjava;
    private javax.swing.JButton jButtonPretraga;
    private javax.swing.JButton jButtonResetujPretragu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelUlogovani;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemOdjava;
    private javax.swing.JMenuItem jMenuItemRadSaAranzmanima;
    private javax.swing.JMenuItem jMenuItemRadSaKlijentima;
    private javax.swing.JMenuItem jMenuItemRadSaUslugama;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRezervacije;
    private javax.swing.JTable jTableStavkeRezervacije;
    private javax.swing.JTextField jTextFieldEmail;
    // End of variables declaration//GEN-END:variables

    public void odjavaActListener(ActionListener actionListener) {
        jButtonOdjava.addActionListener(actionListener);
    }

    public void ugasiFormu() {
        this.dispose();
    }

    public JTable getjTableRezervacije() {
        return jTableRezervacije;
    }

    public void setjTableRezervacije(JTable jTableRezervacije) {
        this.jTableRezervacije = jTableRezervacije;
    }

    public JTable getjTableStavkeRezervacije() {
        return jTableStavkeRezervacije;
    }

    public void setjTableStavkeRezervacije(JTable jTableStavkeRezervacije) {
        this.jTableStavkeRezervacije = jTableStavkeRezervacije;
    }

    public void napraviRezervacijuActListener(ActionListener actionListener) {
        jButtonNapraviRezervaciju.addActionListener(actionListener);
    }

    public void izmeniRezervacijuActListener(ActionListener actionListener) {
        jButtonIzmeniRezervaciju.addActionListener(actionListener);
    }

    public void izbrisiRezervacijuActListener(ActionListener actionListener) {
        jButtonObrisiRezervaciju.addActionListener(actionListener);
    }

    public void pretragaActListener(ActionListener actionListener) {
        jButtonPretraga.addActionListener(actionListener);
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public void setjTextFieldEmail(JTextField jTextFieldEmail) {
        this.jTextFieldEmail = jTextFieldEmail;
    }

    public void resetujPretraguActListener(ActionListener actionListener) {
        jButtonResetujPretragu.addActionListener(actionListener);
    }

}
